-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 4, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 48.654 sec <<< FAILURE! - in TestSuite
loginTest(page_objects_test.LoginPageTest)  Time elapsed: 13.172 sec  <<< FAILURE!
java.lang.AssertionError: expected [This is test data 1] but found [There is 1 error]
	at page_objects_test.LoginPageTest.loginTest(LoginPageTest.java:50)

loginTest(page_objects_test.LoginPageTest)  Time elapsed: 2.754 sec  <<< FAILURE!
java.lang.AssertionError: expected [This is test data 2] but found [There is 1 error]
	at page_objects_test.LoginPageTest.loginTest(LoginPageTest.java:50)

loginTest(page_objects_test.LoginPageTest)  Time elapsed: 2.574 sec  <<< FAILURE!
java.lang.AssertionError: expected [This is test data 3] but found [There is 1 error]
	at page_objects_test.LoginPageTest.loginTest(LoginPageTest.java:50)

